name: core
version: 0.0.1
environment:
  sdk: ^3.13.1
resolution: workspace

dependencies:
  dart_mappable: ^4.8.0
  dio: ^5.11.0
  flutter:
    sdk: flutter
  injectable: ^3.0.0
dev_dependencies:
  build_runner: ^2.16.0
  injectable_generator: ^3.1.3
